# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "gtfcollapser"
description: write your description here
keywords:
  - isoforms
  - transcripts
  - RNAseq
tools:
  - "collapse_annotation.py":
      description: "Collapse isoforms into single transcript per gene and remove overlapping intervals between genes."
      homepage: "https://github.com/broadinstitute/gtex-pipeline/blob/master/gene_model/collapse_annotation.py"
      documentation: "None"
      tool_dev_url: "None"
      doi: ""
      licence: ["MIT"]

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - gtf:
        type: file
        description: Gene Transfer Format file
        pattern: "*.{gtf,gtf.gz}"
        ontologies:
          - edam: "http://edamontology.org/format_2306" # GTF

output:
  bam:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "core_gtf":
          type: file
          description: Sorted BAM/CRAM/SAM file
          pattern: "*.{core.gtf.gz}"
          ontologies:
            - edam: "http://edamontology.org/format_2306" # GTF
  versions_gtfcollapser:
    - - "${task.process}":
          type: string
          description: The name of the process
      - "gtfcollapser":
          type: string
          description: The name of the tool
      - "gtfcollapser --version":
          type: eval
          description: The expression to obtain the version of the tool

topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - gtfcollapser:
          type: string
          description: The name of the module

authors:
  - "@jblancoheredia"
maintainers:
  - "@jblancoheredia"
