name: fgbio_groupreadsbyumi
description: |
  Groups reads together that appear to have come from the same original molecule.
keywords:
  - UMI
  - groupreads
  - fgbio
tools:
  - fgbio:
      description: A set of tools for working with genomic and high throughput sequencing data, including UMIs
      homepage: http://fulcrumgenomics.github.io/fgbio/
      documentation: http://fulcrumgenomics.github.io/fgbio/tools/latest/
      tool_dev_url: https://github.com/fulcrumgenomics/fgbio
      doi: ""
      licence: ["MIT"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - mapped_bam:
      type: file
      description: |
        BAM file.
      pattern: "*.bam"
  - strategy:
      type: value
      description: |
        The UMI assignment strategy.
        Must be chosen among: Identity, Edit, Adjacency, Paired.
  - edit:
      type: value
      description: |
        The allowable number of edits between UMIs

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - bam:
      type: file
      description: UMI-grouped BAM
      pattern: "*.grouped.bam"
  - histogram:
      type: file
      description: A text file containing the tag family size counts
      pattern: "*.grouped-family-sizes.txt"

authors:
  - "@lescai"
